### ISSUE TITLE
Matlab version issue

### ISSUE THREAD

**Issue by yuzi0537** [janinethoma/image_navigation_matlab#4]
Hi Janine,

Thanks for the public code first. When I run the demo.m file, there is a problem popped out, which is
Java exception occurred:
Index (22045) is out of bounds
	at mosek.fusion.PickVariable.<init>(Unknown Source)
	at mosek.fusion.BaseVariable.pick(Unknown Source)

What is that and how can I fix this problem? Thanks

**Comment by yuzi0537** [comment]
My Matlab version is 2021b and the mosek version is 8.

**Comment by janinethoma** [comment]
Hi,

Thank you for trying my public code. Sadly, I no longer have access to Matlab and can't look into the problem. My best guess is: 1) Mosek changed their api, 2) the input data is an edge case I forgot to test against.

If you are able to fix this on your end. I will happily accept a pull request.

Best regards and all the best for your project
Janine



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
